export const EQUIPMENT_LABELS: Record<string, string> = {
  van: 'Dry Van',
  reefer: 'Reefer',
  flatbed: 'Flatbed',
  step_deck: 'Step Deck',
  lowboy: 'Lowboy',
  tanker: 'Tanker',
  box_truck: 'Box Truck',
  sprinter: 'Sprinter',
};

export const EQUIPMENT_CODES: Record<string, string> = {
  van: 'V',
  reefer: 'R',
  flatbed: 'F',
  step_deck: 'S',
  lowboy: 'L',
  tanker: 'T',
  box_truck: 'B',
  sprinter: 'SP',
};

export const LOAD_STATUS_LABELS: Record<string, string> = {
  draft: 'Draft',
  posted: 'Posted',
  bid_received: 'Bid Received',
  awarded: 'Awarded',
  dispatched: 'Dispatched',
  in_transit: 'In Transit',
  delivered: 'Delivered',
  completed: 'Completed',
  cancelled: 'Cancelled',
  expired: 'Expired',
};

export const LOAD_STATUS_COLORS: Record<string, string> = {
  draft: 'text-zinc-400',
  posted: 'text-blue-400',
  bid_received: 'text-yellow-400',
  awarded: 'text-purple-400',
  dispatched: 'text-orange-400',
  in_transit: 'text-orange-500',
  delivered: 'text-green-400',
  completed: 'text-green-500',
  cancelled: 'text-red-400',
  expired: 'text-zinc-500',
};

export const US_STATES = [
  'AL',
  'AK',
  'AZ',
  'AR',
  'CA',
  'CO',
  'CT',
  'DE',
  'FL',
  'GA',
  'HI',
  'ID',
  'IL',
  'IN',
  'IA',
  'KS',
  'KY',
  'LA',
  'ME',
  'MD',
  'MA',
  'MI',
  'MN',
  'MS',
  'MO',
  'MT',
  'NE',
  'NV',
  'NH',
  'NJ',
  'NM',
  'NY',
  'NC',
  'ND',
  'OH',
  'OK',
  'OR',
  'PA',
  'RI',
  'SC',
  'SD',
  'TN',
  'TX',
  'UT',
  'VT',
  'VA',
  'WA',
  'WV',
  'WI',
  'WY',
];

export const ROUTES = {
  SPLASH: '/',
  ONBOARDING: '/onboarding',
  LOGIN: '/login',
  REGISTER: '/register',
  CARRIER: '/carrier',
  CARRIER_LOADS: '/carrier/loads',
  CARRIER_FLEET: '/carrier/fleet',
  BROKER: '/broker',
  BROKER_LOADS: '/broker/loads',
  BROKER_TRUCKS: '/broker/trucks',
  SHIPPER: '/shipper',
  SHIPPER_BOOK: '/shipper/book',
  TRACKING: '/track',
  MESSAGES: '/messages',
  PROFILE: '/profile',
} as const;
