#!/usr/bin/env node
/**
 * FreightX Audit Script
 * Runs on every git push (via pre-push hook).
 * Outputs a timestamped audit report to test/audits/
 */

import { readFileSync, writeFileSync, readdirSync, existsSync } from 'fs';
import { execSync } from 'child_process';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');

const now = new Date();
const timestamp = now.toISOString().replace(/[:.]/g, '-').slice(0, 19);
const dateLabel = now.toLocaleDateString('en-US', {
  weekday: 'long',
  year: 'numeric',
  month: 'long',
  day: 'numeric',
});

// ─── Helpers ──────────────────────────────────────────────────────────────────

function run(cmd) {
  try {
    return execSync(cmd, { cwd: ROOT, encoding: 'utf8' }).trim();
  } catch {
    return '';
  }
}

function countChecked(filePath) {
  if (!existsSync(filePath)) return { checked: 0, total: 0 };
  const content = readFileSync(filePath, 'utf8');
  const total = (content.match(/- \[.\]/g) ?? []).length;
  const checked = (content.match(/- \[x\]/g) ?? []).length;
  return { checked, total };
}

// ─── Git info ─────────────────────────────────────────────────────────────────

const branch = run('git branch --show-current');
const lastCommit = run('git log -1 --pretty="%h — %s"');
const commitCount = run('git rev-list --count HEAD');

// ─── Phase checklist audit ────────────────────────────────────────────────────

const phases = [0, 1, 2, 3, 4, 5, 6];
const phaseResults = phases.map((n) => {
  const file = join(ROOT, `docs/PHASE${n}_GUIDE.md`);
  const { checked, total } = countChecked(file);
  const pct = total ? Math.round((checked / total) * 100) : 0;
  const status =
    total === 0 ? '—' : checked === total ? '✅ Complete' : `🔄 ${pct}% (${checked}/${total})`;
  return `  Phase ${n}: ${status}`;
});

// ─── Test features inventory ──────────────────────────────────────────────────

const testFeaturesDir = join(ROOT, 'test/test-features');
const testFiles = existsSync(testFeaturesDir)
  ? readdirSync(testFeaturesDir).filter((f) => f.endsWith('.test.ts'))
  : [];

// ─── Feature files inventory ──────────────────────────────────────────────────

const featuresDir = join(ROOT, 'apps/web/src/features');
const features = existsSync(featuresDir) ? readdirSync(featuresDir) : [];

const servicesDir = join(ROOT, 'apps/web/src/services');
const services = existsSync(servicesDir)
  ? readdirSync(servicesDir).filter((f) => f.endsWith('.service.ts'))
  : [];

// ─── Build report ─────────────────────────────────────────────────────────────

const report = `# FreightX Audit Report
Generated: ${dateLabel}
Branch: ${branch}
Commits: ${commitCount}
Last commit: ${lastCommit}

---

## Phase Checklist Progress

${phaseResults.join('\n')}

---

## Features Tracked

${features.map((f) => `  - ${f}`).join('\n') || '  (none found)'}

## Services

${services.map((s) => `  - ${s}`).join('\n') || '  (none found)'}

---

## Test Coverage

Test scripts in test/test-features/:
${testFiles.map((f) => `  ✓ ${f}`).join('\n') || '  (none)'}

Features without a test file:
${
  features
    .filter((f) => !testFiles.some((t) => t.startsWith(f)))
    .map((f) => `  ⚠ ${f} — no test file`)
    .join('\n') || '  All features covered'
}

---

## Typecheck

${run('pnpm typecheck 2>&1') ? 'See CI output for typecheck results.' : '✅ No typecheck errors'}

---

_Auto-generated by scripts/audit.js on git push_
`;

const outPath = join(ROOT, `test/audits/audit-${timestamp}.md`);
writeFileSync(outPath, report, 'utf8');
console.log(`\n📋 Audit written → test/audits/audit-${timestamp}.md\n`);
